//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Combo()
        {
            this.Ticket_Combo = new HashSet<Ticket_Combo>();
        }
    
        public int ID_combo { get; set; }
        public string Combo_code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_restaurant { get; set; }
        public Nullable<int> ID_hotel { get; set; }
        public Nullable<int> ID_airline { get; set; }
        public Nullable<int> ID_tour { get; set; }
        public Nullable<int> ID_service { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Service Service { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Combo> Ticket_Combo { get; set; }
    }
}
