//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int ID_orderdetails { get; set; }
        public string Name_ticket { get; set; }
        public string Payment_method { get; set; }
        public string Numberof_ticket { get; set; }
        public decimal Total_price { get; set; }
        public Nullable<int> ID_order { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
