//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Comboes = new HashSet<Combo>();
        }
    
        public int ID_restaurant { get; set; }
        public string Name { get; set; }
        public string Res_Code { get; set; }
        public string Description { get; set; }
        public System.TimeSpan Time_open { get; set; }
        public string Time_close { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Menu { get; set; }
        public Nullable<int> ID_service { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combo> Comboes { get; set; }
        public virtual Service Service { get; set; }
    }
}
