//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int ID_room { get; set; }
        public string Room_code { get; set; }
        public string Name { get; set; }
        public int Numberof_room { get; set; }
        public string Evaluate { get; set; }
        public string Image { get; set; }
        public string Note { get; set; }
        public Nullable<int> ID_hotel { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
