//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_ticket { get; set; }
        public string Name { get; set; }
        public string Ticket_code { get; set; }
        public int Numberof_ticket { get; set; }
        public int Ticket_leave { get; set; }
        public int Remaining_ticket { get; set; }
        public decimal Price { get; set; }
        public string Note { get; set; }
        public Nullable<int> ID_tour_outside { get; set; }
        public Nullable<int> ID_tour_inside { get; set; }
    
        public virtual Tour_Inside Tour_Inside { get; set; }
        public virtual Tour_Outside Tour_Outside { get; set; }
    }
}
